#ifndef TDALISTADOBLEMENTEENLAZADADINAMICA_H
#define TDALISTADOBLEMENTEENLAZADADINAMICA_H

#include "../Nodo/NodoD.h"
#define TODO_OK 0
#define DUPLICADO 1
#define SIN_MEM 2

typedef NodoD* Lista;

#endif // TDALISTADOBLEMENTEENLAZADADINAMICA_H
